In [1]:
import pandas as pd

In [33]:
dataframe = pd.read_csv('./graduate-admissions/Admission_Predict.csv')

In [34]:
dataframe.describe()

,SerialNo,GREScore,TOEFLScore,UniversityRating,SOP,LOR,CGPA,Research,ChanceofAdmit
count,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000
mean,200.500000,316.807500,107.410000,3.087500,3.400000,3.452500,8.598925,0.547500,0.724350
std,115.614301,11.473646,6.069514,1.143728,1.006869,0.898478,0.596317,0.498362,0.142609
min,1.000000,290.000000,92.000000,1.000000,1.000000,1.000000,6.800000,0.000000,0.340000
25%,100.750000,308.000000,103.000000,2.000000,2.500000,3.000000,8.170000,0.000000,0.640000
50%,200.500000,317.000000,107.000000,3.000000,3.500000,3.500000,8.610000,1.000000,0.730000
75%,300.250000,325.000000,112.000000,4.000000,4.000000,4.000000,9.062500,1.000000,0.830000
max,400.000000,340.000000,120.000000,5.000000,5.000000,5.000000,9.920000,1.000000,0.970000

In [35]:
dataframe['GREScore'] /= 316.807500
dataframe['TOEFLScore'] /= 107.410000
dataframe['UniversityRating'] /= 3.087500
dataframe['SOP'] /= 3.4
dataframe['LOR'] /= 3.4525
dataframe['CGPA'] /= 8.598925

dataframe.describe()

,SerialNo,GREScore,TOEFLScore,UniversityRating,SOP,LOR,CGPA,Research,ChanceofAdmit
count,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000
mean,200.500000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.547500,0.724350
std,115.614301,0.036216,0.056508,0.370438,0.296138,0.260240,0.069348,0.498362,0.142609
min,1.000000,0.915382,0.856531,0.323887,0.294118,0.289645,0.790797,0.000000,0.340000
25%,100.750000,0.972199,0.958942,0.647773,0.735294,0.868936,0.950119,0.000000,0.640000
50%,200.500000,1.000608,0.996183,0.971660,1.029412,1.013758,1.001288,1.000000,0.730000
75%,300.250000,1.025860,1.042733,1.295547,1.176471,1.158581,1.053911,1.000000,0.830000
max,400.000000,1.073207,1.117214,1.619433,1.470588,1.448226,1.153633,1.000000,0.970000

In [36]:
dataframe.isnull().sum()

SerialNo            0
GREScore            0
TOEFLScore          0
UniversityRating    0
SOP                 0
LOR                 0
CGPA                0
Research            0
ChanceofAdmit       0
dtype: int64

In [37]:
target = dataframe['ChanceofAdmit']
dataframe = dataframe.drop(['ChanceofAdmit'],axis=1)
dataframe.describe()

,SerialNo,GREScore,TOEFLScore,UniversityRating,SOP,LOR,CGPA,Research
count,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000
mean,200.500000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.547500
std,115.614301,0.036216,0.056508,0.370438,0.296138,0.260240,0.069348,0.498362
min,1.000000,0.915382,0.856531,0.323887,0.294118,0.289645,0.790797,0.000000
25%,100.750000,0.972199,0.958942,0.647773,0.735294,0.868936,0.950119,0.000000
50%,200.500000,1.000608,0.996183,0.971660,1.029412,1.013758,1.001288,1.000000
75%,300.250000,1.025860,1.042733,1.295547,1.176471,1.158581,1.053911,1.000000
max,400.000000,1.073207,1.117214,1.619433,1.470588,1.448226,1.153633,1.000000

In [38]:
target.describe()

count    400.000000
mean       0.724350
std        0.142609
min        0.340000
25%        0.640000
50%        0.730000
75%        0.830000
max        0.970000
Name: ChanceofAdmit, dtype: float64

In [39]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(dataframe,target, test_size = 0.25, random_state = 0)

In [40]:
X_train = X_train.drop(['SerialNo'],axis=1)

In [41]:
X_train.describe()

,GREScore,TOEFLScore,UniversityRating,SOP,LOR,CGPA,Research
count,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000
mean,0.999534,1.000093,1.008367,1.011765,1.011827,1.001617,0.560000
std,0.037355,0.057701,0.379339,0.306601,0.263249,0.071108,0.497216
min,0.915382,0.856531,0.323887,0.294118,0.289645,0.790797,0.000000
25%,0.972199,0.958942,0.647773,0.735294,0.868936,0.950119,0.000000
50%,1.000608,0.996183,0.971660,1.029412,1.013758,1.002451,1.000000
75%,1.025860,1.042733,1.295547,1.176471,1.158581,1.055946,1.000000
max,1.073207,1.117214,1.619433,1.470588,1.448226,1.153633,1.000000

In [42]:
X_test = X_test.drop(['SerialNo'],axis=1)

In [43]:
y_train.describe()

count    300.000000
mean       0.726233
std        0.145906
min        0.340000
25%        0.640000
50%        0.730000
75%        0.840000
max        0.970000
Name: ChanceofAdmit, dtype: float64

In [45]:
X_test

,GREScore,TOEFLScore,UniversityRating,SOP,LOR,CGPA,Research
132,0.975356,0.977563,1.619433,1.029412,1.013758,0.995473,0
309,0.972199,1.024113,1.295547,1.029412,0.868936,1.000125,0
341,1.029016,1.024113,0.971660,1.029412,1.013758,1.018732,1
196,0.965886,0.977563,0.647773,0.882353,0.724113,0.960585,0
246,0.997451,0.977563,0.971660,0.882353,1.013758,1.015243,0
60,0.975356,0.931012,0.647773,0.882353,0.868936,0.941978,0
155,0.984825,1.014803,0.971660,0.882353,0.868936,1.010591,0
261,0.984825,0.968252,0.971660,1.029412,1.158581,0.940815,0
141,1.047955,1.098594,0.647773,1.323529,1.013758,1.088508,1
214,1.044798,1.089284,1.295547,1.323529,1.448226,1.095486,1
37,0.946947,0.977563,0.323887,0.294118,0.579290,0.907090,0
134,1.051111,1.052044,1.619433,1.176471,1.158581,1.079205,1
113,1.010077,1.024113,0.647773,1.176471,1.013758,0.995473,0
348,0.953260,0.921702,0.323887,0.588235,0.579290,0.843129,0
12,1.035329,1.042733,1.295547,1.176471,1.303403,1.058272,1
59,0.981669,0.968252,0.647773,0.588235,0.579290,0.965237,0
293,0.984825,0.912392,0.323887,1.029412,0.868936,0.951282,1
140,1.038486,1.024113,0.647773,1.176471,0.868936,1.064086,1
206,0.994295,0.921702,0.647773,1.029412,0.868936,0.917557,0
199,0.987982,0.996183,0.971660,1.176471,1.303403,1.010591,0
176,1.038486,1.107904,1.295547,1.323529,1.303403,1.065249,1
268,1.032173,1.052044,1.295547,1.323529,1.448226,1.062924,0
124,0.950104,0.986873,1.295547,0.735294,0.868936,0.985007,0
344,0.931165,0.893772,0.647773,0.441176,0.579290,0.853595,0
175,1.010077,1.033423,1.295547,1.323529,1.013758,1.031524,1
313,0.950104,0.931012,0.971660,1.029412,0.868936,0.935001,0
78,0.934321,0.884461,0.647773,0.882353,0.579290,0.876854,1
15,0.991138,0.977563,0.971660,1.029412,0.724113,0.965237,0
286,1.060581,1.098594,1.619433,1.323529,1.158581,1.068738,1
102,0.991138,0.986873,0.647773,1.176471,1.013758,0.959422,0
...,...,...,...,...,...,...,...
7,0.972199,0.940322,0.647773,0.882353,1.158581,0.918719,0
260,1.032173,1.005493,1.619433,1.470588,1.013758,1.061761,1
68,1.003764,1.014803,0.971660,1.029412,1.158581,1.072227,1
20,0.984825,0.996183,0.971660,0.882353,0.579290,0.918719,1
107,1.066894,1.089284,1.295547,1.029412,1.303403,1.100138,1
14,0.981669,0.968252,0.971660,1.029412,0.579290,0.953608,1
363,0.965886,0.958942,0.647773,0.735294,0.868936,0.972215,0
304,0.987982,0.986873,0.647773,0.735294,0.579290,0.980355,0
361,1.054268,1.079974,1.295547,1.176471,1.013758,1.109441,1
329,0.937478,0.893772,0.647773,0.735294,0.434468,0.917557,0
336,1.006921,1.024113,0.971660,0.882353,0.724113,1.022221,0
64,1.025860,1.033423,0.971660,0.882353,1.013758,1.011754,0
55,1.010077,0.958942,0.971660,0.882353,0.868936,0.895461,0
106,1.038486,1.033423,1.295547,1.323529,1.303403,1.067575,1
300,0.975356,0.986873,0.647773,0.735294,0.724113,0.930349,0
229,1.022703,1.033423,1.295547,0.882353,0.868936,1.047805,1
122,0.978512,0.986873,1.295547,0.441176,0.724113,0.972215,0
373,1.013234,1.014803,0.971660,0.882353,0.868936,0.993147,1
395,1.022703,1.024113,0.971660,1.029412,1.013758,1.051294,1
325,1.029016,1.079974,0.971660,1.029412,1.158581,1.062924,1
380,1.016390,0.968252,0.971660,1.029412,1.158581,1.028035,1
253,1.057424,1.070664,1.295547,1.323529,1.303403,1.125722,1
56,0.997451,0.949632,0.971660,0.588235,0.868936,0.860573,0
8,0.953260,0.949632,0.323887,0.588235,0.434468,0.930349,0
190,1.022703,1.033423,1.619433,1.323529,1.158581,1.065249,1
146,0.994295,0.977563,0.971660,0.588235,0.724113,0.986170,0
135,0.991138,1.014803,1.295547,1.029412,1.158581,1.019895,1
390,0.991138,0.949632,0.647773,0.588235,0.724113,0.958259,0
264,1.025860,1.024113,0.647773,0.882353,0.724113,1.018732,1
364,0.987982,0.949632,0.971660,1.029412,1.158581,1.035013,1

In [46]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score

In [47]:
model = LinearRegression()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
# accuracy = model.score(X_test,y_test)

In [58]:
from sklearn import metrics
import numpy as np
print(metrics.mean_squared_error(y_test,y_pred))
print(metrics.mean_absolute_error(y_test,y_pred))
print(np.sqrt(metrics.mean_squared_error(y_test,y_pred)))

0.004801498976816873
0.049113635308592
0.06929284939167152

In [59]:
from sklearn.svm import SVR
model_svr = SVR(kernel='rbf')
model_svr.fit(X_train,y_train)
y_pred_svr = model_svr.predict(X_test)

C:\Users\Rajat\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)

In [60]:
print(metrics.mean_squared_error(y_test,y_pred_svr))
print(metrics.mean_absolute_error(y_test,y_pred_svr))
print(np.sqrt(metrics.mean_squared_error(y_test,y_pred_svr)))

0.006056621326365902
0.06489232288534717
0.07782429778909607